#!/bin/sh
# Writes config.php from environment variables and prepares the storage
# volume, then hands over to the image's command (apache2-foreground).
set -e

cd /var/www/html

# A freshly created (empty) storage volume needs the folder skeleton.
for dir in backups cache logs sessions uploads; do
    if [ ! -d "storage/$dir" ]; then
        cp -a "/usr/src/easyappointments-storage/$dir" "storage/$dir"
    fi
done
chown -R www-data:www-data storage

if [ -z "$DB_PASSWORD" ]; then
    echo "easyappointments: DB_PASSWORD is not set" >&2
    exit 1
fi

php <<'PHP'
<?php
function env_value(string $name, string $default = ''): string
{
    $value = getenv($name);

    return $value === false || $value === '' ? $default : $value;
}

$constants = [
    'BASE_URL' => rtrim(env_value('BASE_URL', 'http://localhost'), '/'),
    'LANGUAGE' => env_value('LANGUAGE', 'english'),
    'DEBUG_MODE' => filter_var(env_value('DEBUG_MODE', 'false'), FILTER_VALIDATE_BOOLEAN),
    'DB_HOST' => env_value('DB_HOST', 'db'),
    'DB_NAME' => env_value('DB_NAME', 'easyappointments'),
    'DB_USERNAME' => env_value('DB_USERNAME', 'easyappointments'),
    'DB_PASSWORD' => env_value('DB_PASSWORD'),
    'GOOGLE_SYNC_FEATURE' => filter_var(env_value('GOOGLE_SYNC_FEATURE', 'false'), FILTER_VALIDATE_BOOLEAN),
    'GOOGLE_CLIENT_ID' => env_value('GOOGLE_CLIENT_ID'),
    'GOOGLE_CLIENT_SECRET' => env_value('GOOGLE_CLIENT_SECRET'),
];

if (env_value('DEFAULT_BOOKING_STEP_ORDER') !== '') {
    $constants['DEFAULT_BOOKING_STEP_ORDER'] = env_value('DEFAULT_BOOKING_STEP_ORDER');
}

$config = "<?php\n// Generated by the Docker entrypoint from environment variables, do not edit.\n";

if (env_value('ENCRYPTION_KEY') !== '') {
    $config .= 'define(\'ENCRYPTION_KEY\', ' . var_export(env_value('ENCRYPTION_KEY'), true) . ");\n";
}

$config .= "\nclass Config\n{\n";

foreach ($constants as $name => $value) {
    $config .= '    const ' . $name . ' = ' . var_export($value, true) . ";\n";
}

$config .= "}\n";

file_put_contents('/var/www/html/config.php', $config);
chown('/var/www/html/config.php', 'www-data');
chmod('/var/www/html/config.php', 0640);
PHP

# Bring an already installed database up to date, so updates that add columns (e.g. the provider meeting link)
# need no manual step. A fresh database is left alone: the web installer creates it. Data is never touched, the
# migrations only add what is missing.
state=1
i=0
while [ "$i" -lt 30 ]; do
    state=0
    php <<'PHP' || state=$?
<?php
mysqli_report(MYSQLI_REPORT_OFF);
$db = @new mysqli(getenv('DB_HOST') ?: 'db', getenv('DB_USERNAME') ?: 'easyappointments', getenv('DB_PASSWORD'), getenv('DB_NAME') ?: 'easyappointments');
if ($db->connect_errno) {
    exit(1);
}
exit($db->query('SELECT 1 FROM ea_migrations LIMIT 1') ? 0 : 2);
PHP
    [ "$state" -ne 1 ] && break
    i=$((i + 1))
    sleep 2
done

if [ "$state" -eq 0 ]; then
    echo "easyappointments: applying pending database migrations"
    su -s /bin/sh www-data -c "cd /var/www/html && php index.php console migrate" ||
        echo "easyappointments: migration failed, see the output above" >&2
elif [ "$state" -eq 1 ]; then
    echo "easyappointments: database not reachable, skipping migrations" >&2
fi

exec docker-php-entrypoint "$@"
