#!/bin/sh
# Writes config.php from environment variables and prepares the storage
# volume, then hands over to the image's command (apache2-foreground).
set -e

cd /var/www/html

# A freshly created (empty) storage volume needs the folder skeleton.
for dir in backups cache logs sessions uploads; do
    if [ ! -d "storage/$dir" ]; then
        cp -a "/usr/src/easyappointments-storage/$dir" "storage/$dir"
    fi
done
chown -R www-data:www-data storage

if [ -z "$DB_PASSWORD" ]; then
    echo "easyappointments: DB_PASSWORD is not set" >&2
    exit 1
fi

php <<'PHP'
<?php
function env_value(string $name, string $default = ''): string
{
    $value = getenv($name);

    return $value === false || $value === '' ? $default : $value;
}

$constants = [
    'BASE_URL' => rtrim(env_value('BASE_URL', 'http://localhost'), '/'),
    'LANGUAGE' => env_value('LANGUAGE', 'english'),
    'DEBUG_MODE' => filter_var(env_value('DEBUG_MODE', 'false'), FILTER_VALIDATE_BOOLEAN),
    'DB_HOST' => env_value('DB_HOST', 'db'),
    'DB_NAME' => env_value('DB_NAME', 'easyappointments'),
    'DB_USERNAME' => env_value('DB_USERNAME', 'easyappointments'),
    'DB_PASSWORD' => env_value('DB_PASSWORD'),
    'GOOGLE_SYNC_FEATURE' => filter_var(env_value('GOOGLE_SYNC_FEATURE', 'false'), FILTER_VALIDATE_BOOLEAN),
    'GOOGLE_CLIENT_ID' => env_value('GOOGLE_CLIENT_ID'),
    'GOOGLE_CLIENT_SECRET' => env_value('GOOGLE_CLIENT_SECRET'),
];

if (env_value('DEFAULT_BOOKING_STEP_ORDER') !== '') {
    $constants['DEFAULT_BOOKING_STEP_ORDER'] = env_value('DEFAULT_BOOKING_STEP_ORDER');
}

$config = "<?php\n// Generated by the Docker entrypoint from environment variables, do not edit.\n";

if (env_value('ENCRYPTION_KEY') !== '') {
    $config .= 'define(\'ENCRYPTION_KEY\', ' . var_export(env_value('ENCRYPTION_KEY'), true) . ");\n";
}

$config .= "\nclass Config\n{\n";

foreach ($constants as $name => $value) {
    $config .= '    const ' . $name . ' = ' . var_export($value, true) . ";\n";
}

$config .= "}\n";

file_put_contents('/var/www/html/config.php', $config);
chown('/var/www/html/config.php', 'www-data');
chmod('/var/www/html/config.php', 0640);
PHP

exec docker-php-entrypoint "$@"
